import { GoogleGenAI, Type } from "@google/genai";
const getApiKey = () => {
    if (typeof process !== 'undefined' && process.env) {
        if (process.env.GEMINI_API_KEY)
            return process.env.GEMINI_API_KEY;
        if (process.env.REACT_APP_GEMINI_API_KEY)
            return process.env.REACT_APP_GEMINI_API_KEY;
        if (process.env.VITE_GEMINI_API_KEY)
            return process.env.VITE_GEMINI_API_KEY;
    }
    if (typeof import.meta !== 'undefined' && import.meta?.env) {
        if (import.meta.env.VITE_GEMINI_API_KEY)
            return import.meta.env.VITE_GEMINI_API_KEY;
        if (import.meta.env.GEMINI_API_KEY)
            return import.meta.env.GEMINI_API_KEY;
    }
    return '';
};
const apiKey = getApiKey();
const ai = new GoogleGenAI({ apiKey: apiKey || 'PLACEHOLDER_KEY' });
// Helper to check key
const checkApiKey = () => {
    const key = getApiKey();
    if (!key || key === 'PLACEHOLDER_API_KEY' || key === 'PLACEHOLDER_KEY') {
        throw new Error("API Key not found or invalid. Please set your GEMINI_API_KEY or REACT_APP_GEMINI_API_KEY in environment variables.");
    }
};
// 1. Generate Floor Plan Image (2D)
export const generateFloorPlanImage = async (prompt, imageBase64) => {
    checkApiKey();
    const contents = {
        parts: []
    };
    if (imageBase64) {
        // Image-to-Image Generation (Sketch to Plan)
        const mimeType = imageBase64.substring(imageBase64.indexOf(':') + 1, imageBase64.indexOf(';'));
        const data = imageBase64.split(',')[1];
        contents.parts.push({
            inlineData: {
                mimeType: mimeType,
                data: data
            }
        });
        const textPrompt = prompt
            ? `Refine this sketch into a professional 2D CAD floor plan. Requirements: ${prompt}. Clean lines, white background.`
            : "Refine this rough sketch into a professional, clean 2D CAD floor plan. Black lines, white background.";
        contents.parts.push({ text: textPrompt });
    }
    else {
        // Text-to-Image Generation
        const systemPrompt = "Generate a professional, high-contrast 2D architectural floor plan schematic with black lines on a white background. It should look like a CAD drawing.";
        contents.parts.push({ text: `${systemPrompt} Description: ${prompt}` });
    }
    const response = await ai.models.generateContent({
        model: 'gemini-2.0-flash',
        contents: contents,
    });
    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }
    throw new Error("No image generated by the AI model. Ensure you are using a model that supports image generation.");
};
// 1b. Generate 3D Perspective (Simulated Walkthrough)
export const generate3DView = async (prompt) => {
    checkApiKey();
    const response = await ai.models.generateContent({
        model: 'gemini-2.0-flash',
        contents: {
            parts: [{ text: `Generate a photorealistic 3D interior perspective view (walkthrough shot) for this architectural description: ${prompt}. Eye-level view, realistic lighting, modern interior design.` }]
        }
    });
    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }
    throw new Error("No 3D view generated.");
};
// 2. Cost Estimation (BOQ) Generation - Optimized for Speed
export const generateBOQ = async (projectDescription) => {
    checkApiKey();
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: `Generate a concise Bill of Quantities (BOQ) for: "${projectDescription}". 
    Return 5-10 major line items with estimated quantities and market rates in INR.
    Use high-level estimates to be fast.`,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        item: { type: Type.STRING },
                        description: { type: Type.STRING },
                        quantity: { type: Type.NUMBER },
                        unit: { type: Type.STRING },
                        rate: { type: Type.NUMBER },
                        amount: { type: Type.NUMBER }
                    },
                    required: ["item", "description", "quantity", "unit", "rate", "amount"]
                }
            }
        }
    });
    return JSON.parse(response.text || "[]");
};
// 3. Workflow & Safety Suggestions
export const getWorkflowSuggestions = async (context) => {
    checkApiKey();
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: `Context: Construction site. Situation: "${context}". Give 3 quick safety tips.`
    });
    return response.text;
};
// 4. Chat Assistant
export const createChatSession = (systemInstruction) => {
    checkApiKey();
    return ai.chats.create({
        model: 'gemini-2.0-flash',
        config: {
            systemInstruction
        }
    });
};
// 5. Contract & Tender Generation
export const generateDocument = async (docType, details) => {
    checkApiKey();
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: `Write a professional ${docType} for: ${details}. Format clearly.`
    });
    return response.text || "Failed to generate document.";
};
// 6. Permit & Compliance Generation
export const generatePermitDocument = async (docType, projectDetails) => {
    checkApiKey();
    const prompt = `Generate a "${docType}" for: ${projectDetails}. Adhere to VMC/APCRDA rules.`;
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: prompt
    });
    return response.text || "Failed to generate permit document.";
};
// 7. AI Auto-Scheduling - FIXED with Schema
export const generateConstructionSchedule = async (projectDetails) => {
    checkApiKey();
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: `Generate a construction schedule for: ${projectDetails}.
    Return a valid JSON array of tasks.`,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        id: { type: Type.STRING },
                        phase: { type: Type.STRING },
                        task: { type: Type.STRING },
                        startDay: { type: Type.NUMBER },
                        durationDays: { type: Type.NUMBER },
                        dependencies: { type: Type.ARRAY, items: { type: Type.STRING } },
                        resources: { type: Type.STRING },
                        milestone: { type: Type.BOOLEAN }
                    },
                    required: ["id", "phase", "task", "startDay", "durationDays", "dependencies", "resources", "milestone"]
                }
            }
        }
    });
    return JSON.parse(response.text || "[]");
};
// 8. AI Building Code Checker - FIXED with Schema
export const runComplianceCheck = async (buildingParams) => {
    checkApiKey();
    const schema = {
        type: Type.OBJECT,
        properties: {
            overallStatus: { type: Type.STRING, enum: ["Compliant", "Non-Compliant", "Conditional Approval"] },
            score: { type: Type.NUMBER },
            checks: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        category: { type: Type.STRING },
                        rule: { type: Type.STRING },
                        requirement: { type: Type.STRING },
                        provided: { type: Type.STRING },
                        status: { type: Type.STRING, enum: ["Pass", "Fail", "Warning"] },
                        recommendation: { type: Type.STRING }
                    },
                    required: ["category", "rule", "requirement", "provided", "status", "recommendation"]
                }
            }
        },
        required: ["overallStatus", "score", "checks"]
    };
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: `Check compliance for: ${JSON.stringify(buildingParams)} against NBC 2016 and AP Rules.`,
        config: {
            responseMimeType: "application/json",
            responseSchema: schema
        }
    });
    return JSON.parse(response.text || "{}");
};
// 9. AI BOQ Optimizer
export const generateBOQOptimization = async (boqData, location) => {
    checkApiKey();
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: `Optimize this BOQ for ${location}: ${JSON.stringify(boqData)}. Return array of suggestions.`,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        id: { type: Type.STRING },
                        originalItem: { type: Type.STRING },
                        proposedAlternative: { type: Type.STRING },
                        savingsPercentage: { type: Type.NUMBER },
                        potentialSavingsAmount: { type: Type.NUMBER },
                        reasoning: { type: Type.STRING },
                        implementationStrategy: { type: Type.STRING }
                    },
                    required: ["id", "originalItem", "proposedAlternative", "savingsPercentage", "potentialSavingsAmount", "reasoning", "implementationStrategy"]
                }
            }
        }
    });
    return JSON.parse(response.text || "[]");
};
// 10. Generate Project Outline (New Project Wizard)
export const generateProjectOutline = async (description, budget, location) => {
    checkApiKey();
    const prompt = `Create a high-level construction project outline for a project described as: "${description}".
  Location: ${location}. Budget: ${budget}.
  Provide:
  1. A Project Name
  2. Estimated Duration (months)
  3. 3 Key Construction Stages
  4. 3 Major Material Requirements
  `;
    const response = await ai.models.generateContent({
        model: 'gemini-2.0-flash',
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    suggestedName: { type: Type.STRING },
                    estimatedDurationMonths: { type: Type.NUMBER },
                    stages: { type: Type.ARRAY, items: { type: Type.STRING } },
                    keyMaterials: { type: Type.ARRAY, items: { type: Type.STRING } },
                    briefSummary: { type: Type.STRING }
                },
                required: ["suggestedName", "estimatedDurationMonths", "stages", "keyMaterials", "briefSummary"]
            }
        }
    });
    return JSON.parse(response.text || "{}");
};
