import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { UserRole } from '../types';
import { MOCK_PROJECTS } from '../constants';
import { Plus, Wand2, Calculator } from 'lucide-react';
import NewProjectWizard from './NewProjectWizard';
const ProjectList = ({ onSelectProject, onNewToolsSelect, userRole }) => {
    const [projects, setProjects] = useState(MOCK_PROJECTS);
    const [showWizard, setShowWizard] = useState(false);
    // Filter projects for Client Role (Mock logic: Client only sees 'Shanti Villa' for demo)
    const displayProjects = userRole === UserRole.CLIENT
        ? projects.filter(p => p.id === 'p2')
        : projects;
    const handleProjectCreated = (newProject) => {
        setProjects([...projects, newProject]);
        setShowWizard(false);
        onSelectProject(newProject);
    };
    return (_jsxs("div", { className: "min-h-screen bg-white text-slate-900 font-sans", children: [showWizard && (_jsx(NewProjectWizard, { onClose: () => setShowWizard(false), onProjectCreated: handleProjectCreated })), _jsxs("nav", { className: "flex items-center justify-between px-8 py-6", children: [_jsx("div", { className: "text-xl font-bold text-slate-900 tracking-tight", children: "AIrchitect" }), _jsx("div", { className: "flex items-center gap-4", children: _jsx("div", { className: "w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center border border-slate-200 text-slate-600 font-bold", children: userRole === UserRole.PROJECT_MANAGER ? 'PM' : userRole === UserRole.CLIENT ? 'CL' : 'SM' }) })] }), _jsxs("div", { className: "max-w-7xl mx-auto px-8 py-4", children: [_jsxs("div", { className: "mb-10 pt-4 flex flex-col md:flex-row md:justify-between md:items-end gap-4", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-4xl font-bold text-slate-900 mb-2 tracking-tight", children: "Welcome to AIrchitect" }), _jsx("p", { className: "text-slate-500 text-lg", children: userRole === UserRole.CLIENT
                                            ? "Track your dream project progress."
                                            : "Your intelligent partner in construction management." })] }), userRole === UserRole.PROJECT_MANAGER && (_jsxs("button", { onClick: () => setShowWizard(true), className: "bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 shadow-lg hover:shadow-xl transition-all", children: [_jsx(Plus, { size: 20 }), " Create New Project"] }))] }), userRole === UserRole.PROJECT_MANAGER && (_jsxs("div", { className: "mb-12", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-600 mb-4 uppercase tracking-wide text-xs", children: "Quick Tools" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("button", { onClick: () => onNewToolsSelect('floor'), className: "bg-indigo-50 border border-indigo-100 hover:bg-indigo-100 p-6 rounded-xl flex items-center gap-4 transition-colors text-left", children: [_jsx("div", { className: "p-3 bg-indigo-600 text-white rounded-lg", children: _jsx(Wand2, { size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-indigo-900", children: "AI Floor Plan Generator" }), _jsx("p", { className: "text-sm text-indigo-700", children: "Create new layouts from sketches or prompts." })] })] }), _jsxs("button", { onClick: () => onNewToolsSelect('cost'), className: "bg-green-50 border border-green-100 hover:bg-green-100 p-6 rounded-xl flex items-center gap-4 transition-colors text-left", children: [_jsx("div", { className: "p-3 bg-green-600 text-white rounded-lg", children: _jsx(Calculator, { size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-green-900", children: "Smart Cost Estimator" }), _jsx("p", { className: "text-sm text-green-700", children: "Estimate budgets for new ideas." })] })] })] })] })), _jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-bold text-slate-900 mb-6", children: userRole === UserRole.CLIENT ? "My Project" : "Active Projects" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6", children: displayProjects.map((project) => (_jsxs("div", { onClick: () => onSelectProject(project), className: "bg-white border border-slate-200 rounded-xl overflow-hidden hover:shadow-xl transition-all cursor-pointer group h-[300px] flex flex-col relative", children: [_jsxs("div", { className: "h-44 relative overflow-hidden bg-slate-100", children: [_jsx("img", { src: project.thumbnail, alt: project.name, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" }), _jsx("div", { className: "absolute top-4 right-4", children: _jsxs("span", { className: `px-3 py-1 rounded-full text-xs font-semibold shadow-sm backdrop-blur-md ${project.status === 'In Progress' ? 'bg-yellow-400/90 text-yellow-900' :
                                                            project.status === 'Planning' ? 'bg-blue-400/90 text-blue-900' :
                                                                project.status === 'Completed' ? 'bg-green-400/90 text-green-900' :
                                                                    'bg-slate-200 text-slate-800'}`, children: [project.status === 'In Progress' && _jsx("span", { className: "inline-block w-2 h-2 rounded-full bg-yellow-700 mr-1" }), project.status === 'Planning' && _jsx("span", { className: "inline-block w-2 h-2 rounded-full bg-blue-700 mr-1" }), project.status === 'Completed' && _jsx("span", { className: "inline-block w-2 h-2 rounded-full bg-green-700 mr-1" }), project.status] }) })] }), _jsxs("div", { className: "p-5 flex-1 flex flex-col justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-bold text-xl text-slate-900 mb-1 leading-tight group-hover:text-indigo-600 transition-colors", children: project.name }), _jsx("p", { className: "text-slate-500 text-sm", children: project.location })] }), userRole !== UserRole.CLIENT && (_jsx("div", { className: "text-xs text-slate-400 mt-2", children: "Click to open Explorer" }))] })] }, project.id))) })] })] })] }));
};
export default ProjectList;
